language: go
os:
  - linux
  - osx
go:
  - go1.13.x
env:
 global:
   - GO111MODULE=on
script:
  - go get -t github.com/iris-contrib/middleware/casbin/v12@v12.0.0
  - go get -t github.com/iris-contrib/middleware/cloudwatch/v12@v12.0.0
  - go get -t github.com/iris-contrib/middleware/cors/v12@v12.0.0
  - go get -t github.com/iris-contrib/middleware/csrf/v12@v12.0.0
  - go get -t github.com/iris-contrib/middleware/go-i18n/v12@v12.0.0
  - go get -t github.com/iris-contrib/middleware/jwt/v12@v12.0.0
  - go get -t github.com/iris-contrib/middleware/newrelic/v12@v12.0.0
  - go get -t github.com/iris-contrib/middleware/permissionbolt/v12@v12.0.0
  - go get -t github.com/iris-contrib/middleware/prometheus/v12@v12.0.0
  - go get -t github.com/iris-contrib/middleware/raven/v12@v12.0.0
  - go get -t github.com/iris-contrib/middleware/secure/v12@v12.0.0
  - go get -t github.com/iris-contrib/middleware/tollboothic/v12@v12.0.0
  - go test -v -cover ./casbin/...
  - go test -v -cover ./cloudwatch/...
  - go test -v -cover ./cors/...
  - go test -v -cover ./csrf/...
  - go test -v -cover ./go-i18n/...
  - go test -v -cover ./jwt/...
  - go test -v -cover ./newrelic/...
  - go test -v -cover ./permissionbolt/...
  - go test -v -cover ./prometheus/...
  - go test -v -cover ./raven/...
  - go test -v -cover ./secure/...
  - go test -v -cover ./tollboothic/...
