language: go
sudo: false
os:
  - linux
  - osx
go:
  - 1.15.x
env:
 global:
   - GO111MODULE=on
   - GOPROXY=https://gocenter.io,https://goproxy.io,https://goproxy.cn,direct
before_install:
  - chmod +x .travis.gofmt.sh
  - chmod +x .travis.gotest.sh
script:
  - ./.travis.gofmt.sh
  - ./.travis.gotest.sh
