language: go
sudo: false
os:
  - linux
  - osx
go:
  - go1.14.x
env:
 global:
   - GO111MODULE=on
   - GOPROXY=https://goproxy.io
before_install:
  - chmod +x .travis.gofmt.sh
  - chmod +x .travis.gotest.sh
script:
  - ./.travis.gofmt.sh
  - ./.travis.gotest.sh
